# ------------------------------------------------------------
# ORDER SERVICE
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: order-service
          image: aliceyangac/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: FASTIFY_ADDRESS
              value: "0.0.0.0"
            - name: ASB_QUEUE_NAME
              value: "orders"
            - name: ORDER_DB_NAME
              value: "orderdb"
            - name: ASB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: ASB_CONNECTION_STRING
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: MONGO_URI
          resources:
            requests:
              cpu: 1m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: order-service

---
# ------------------------------------------------------------
# MAKELINE SERVICE
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: makeline-service
          image: aliceyangac/makeline-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: ORDER_QUEUE_NAME
              value: "orders"
            - name: SHIPPING_QUEUE_NAME
              value: "shipping"
            - name: ORDER_DB_NAME
              value: "orderdb"
            - name: ORDER_DB_COLLECTION_NAME
              value: "orders"
            - name: ASB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: ASB_CONNECTION_STRING
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: MONGO_URI
          resources:
            requests:
              cpu: 1m
              memory: 6Mi
            limits:
              cpu: 5m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: makeline-service

---
# ------------------------------------------------------------
# SHIPPING SERVICE
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: shipping-service
          image: aliceyangac/shipping-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: SHIPPING_DB_NAME
              value: "orderdb"
            - name: SHIPPING_QUEUE_NAME
              value: "shipping"
            - name: SHIPPING_DB_COLLECTION_NAME
              value: "orders"
            - name: ASB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: ASB_CONNECTION_STRING
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: MONGO_URI
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3003
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3003
      targetPort: 3003
  selector:
    app: shipping-service

---
# ------------------------------------------------------------
# PRODUCT SERVICE
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: product-service
          image: aliceyangac/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: MONGO_URI
            - name: BLOB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: best-buy-secrets
                  key: BLOB_CONNECTION_STRING
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  selector:
    app: product-service

---
# ------------------------------------------------------------
# STORE FRONT (Vue.js App)
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: store-front
          image: aliceyangac/store-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: store-front
          env:
            # Pointing to Internal K8s Service Names
            - name: VUE_APP_ORDER_SERVICE_URL
              value: "http://order-service:3000/"
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: "http://product-service:3002/"
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: store-front
spec:
  type: LoadBalancer # EXTERNAL
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: store-front

---
# ------------------------------------------------------------
# STORE ADMIN (Vue.js App)
# ------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: store-admin
          image: aliceyangac/store-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: store-admin
          env:
            # Pointing to Internal K8s Service Names
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: "http://product-service:3002/"
            - name: VUE_APP_MAKELINE_SERVICE_URL
              value: "http://makeline-service:3001/"
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: LoadBalancer # EXTERNAL
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: store-admin